### PR TITLE
added Swedish ÅÄÖ as valid input keys

### PR DESCRIPTION
**Pull request by trackd**
Hey,

Cool module, i noticed that 'Å','Ä','Ö' was not allowed as input..

I added them to the enum and `_keyConsoleKeyTable`, i had to modify the `IsAscii` check a bit cause otherwise it wouldn't allow them..

I'm sure theres many more missing.

I think trying to keep this up to date over time could be quite hard.

would probably be easier to just defer to .net using something like:

https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidfilenamechars?view=net-8.0
https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getinvalidpathchars?view=net-8.0

### CODE REVIEW

**Comment by mdgrs-mei** [comment]
@trackd Thank you for the PR. This reminded me that I ignored non-Ascii characters as the initial implementation. All the Japanese characters are ignored too.

Probably this is a better check (it's also used in TextBox.cs):

```c#
if (Unicode.GetDisplayWidth(key.ConsoleKeyInfo.KeyChar) <= 0)
    continue
```

Could you test if this works? This way you don't need to modify Key.cs and KeyInput.cs. I will add wide character handling later.

**Comment by trackd** [comment]
> @trackd Thank you for the PR. This reminded me that I ignored non-Ascii characters as the initial implementation. All the Japanese characters are ignored too.
> 
> Probably this is a better check (it's also used in TextBox.cs):
> 
> ```cs
> if (Unicode.GetDisplayWidth(key.ConsoleKeyInfo.KeyChar) <= 0)
>     continue
> ```
> 
> Could you test if this works? This way you don't need to modify Key.cs and KeyInput.cs. I will add wide character handling later.

Yea that's a good idea, i wasn't super happy with the replacement check i added..

It works with `Unicode.GetDisplayWidth`, just had to add the dependency -> `using PowerShellRun.Dependency;` took a minute to figure that one out ;)

**Comment by mdgrs-mei** [comment]
Thank you!

**Comment by mdgrs-mei** [comment]
@trackd Just wanted to let you know that this issue was addressed in [v0.1.0](https://github.com/mdgrs-mei/PowerShellRun/releases/tag/v0.1.0). Thanks.

**Pull request closed without merging**
