### PR TITLE
Fix small typo in `README.md`

### PR DESCRIPTION
**Pull request by SeeminglyScience**

### CODE REVIEW

**Comment by mdgrs-mei** [comment]
Aha! thank you.

**Comment by mdgrs-mei** [comment]
@SeeminglyScience wait, isn't it still wrong?

**Comment by SeeminglyScience** [comment]
> @SeeminglyScience wait, isn't it still wrong?

LOL it sure is. My bad!

**Comment by mdgrs-mei** [comment]
Never mind I fixed it. Thank you!

**Pull request merged**
